name: booradley
favicon: null
layout_spectrum: 0.74554
typography_spectrum: 0.15956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9375
  lightness: 0.9999125765170902
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
