name: booradley
favicon: null
layout_spectrum: 0.74554
typography_spectrum: 0.15956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f0f0'
    - '#0e0d12'
    - '#262b41'
    - '#5d6476'
    - '#96969e'
  brandStrength: 0.9375
  lightness: 0.9999125765170902
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
